# Generated by Django 5.0.4 on 2024-04-26 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-z- A-z]+$', code='Invalid name', message='Invalide data to the fields........')])),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z- A-z 0-9]+$', code='Invalide name', message='Invalide data to the fields......')])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
