# Generated by Django 5.0.4 on 2024-04-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='catogeries',
        ),
    ]
