# Generated by Django 5.0.4 on 2024-04-26 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blog_catogeries'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='catogeries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blogs.catogeries'),
        ),
    ]
